### ISSUE TITLE
Propuesta de documentación

### ISSUE THREAD

**Issue by delor34n** [delor34n/nemesis_v2#3]
Se me ocurre que sería una buena idea ir documentando en la wiki cada cosa que hagamos  por dos razones:
1. Para ordenarnos.
2. Para ir de a poco documentando las  cosas que hagamos y/o aprendamos, para que así el informe salga de una. Además es un buen ejercicio para que los dos sepamos todo y lo recordemos, sobre todo pensando en que le tenemos que presentar esto al Oscar.

¿Qué crees tú?

**Comment by guatadepez** [comment]
Me tinca caleta wn, sorry por la respuesta tardìa, pero recien entre a la eaa xD

**Comment by delor34n** [comment]
Ok
